#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_dla.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=32 --noc_hops=1 --noc_hop_latency=1 --l1_size=256 --l2_size=2048 --num_pes=256 --print_design_space=true --msg_print_lv=0

#NVDLA of 32x32 PE (same as TPU MACs)
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_dla.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=true --num_pes=1024 --num_simd_lanes=64 --l1_size=44032 --l2_size=256 --print_design_space=true --msg_print_lv=0
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_DLA.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=true --num_pes=1024 --num_simd_lanes=64 --l1_size=44032 --l2_size=256 --print_design_space=true --msg_print_lv=0

#Shi
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_shi.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=44032 --l2_size=256 --print_design_space=true --msg_print_lv=0
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_shi.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=44032 --l2_size=256 --print_design_space=true --msg_print_lv=0

#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_dla.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep Runtime | awk '{print $2}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_shi.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep Runtime | awk '{print $2}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_DLA.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep Runtime | awk '{print $2}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_shi.m' --HW_file='./data/hw/accelerator_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep Runtime | awk '{print $2}' | paste -sd+ - | bc

#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_dla.m' --HW_file='./data/hw/acc_het_1.m' --noc_hop_latency=1 --noc_mc_support=false --num_simd_lanes=1 --print_design_space=true --msg_print_lv=0 | grep "Total energy consumption" | awk '{print ($4*1e0)}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/Resnet50_shi.m' --HW_file='./data/hw/acc_het_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep "Total energy consumption" | awk '{print ($4*1e0)}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_DLA.m' --HW_file='./data/hw/acc_het_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep "Total energy consumption" | awk '{print ($4*1e0)}' | paste -sd+ - | bc
#./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/UNet_shi.m' --HW_file='./data/hw/acc_het_1.m' --noc_bw=256 --noc_hops=1 --noc_hop_latency=1 --noc_mc_support=false --num_pes=65536 --num_simd_lanes=1 --l1_size=16384 --l2_size=8192 --print_design_space=true --msg_print_lv=0 | grep "Total energy consumption" | awk '{print ($4*1e0)}' | paste -sd+ - | bc

#Whole Acc: DLA, SHI
./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/mix_Resnet50_UNet_dla.m' --HW_file='./data/hw/acc_het_whole.m' --noc_hop_latency=1 --noc_mc_support=false --num_simd_lanes=1 --print_design_space=true --msg_print_lv=0 > mix_Resnet50_UNet_dla_acc_whole.log
./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/mix_Resnet50_UNet_shi.m' --HW_file='./data/hw/acc_het_whole.m' --noc_hop_latency=1 --noc_mc_support=false --num_simd_lanes=1 --print_design_space=true --msg_print_lv=0 > mix_Resnet50_UNet_shi_acc_whole.log


#Partitioned Acc: sa1, sa2
./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/mix_Resnet50_UNet_DeepFilters.m' --HW_file='./data/hw/acc_het_sa1.m' --noc_hop_latency=1 --noc_mc_support=false --num_simd_lanes=1 --print_design_space=true --msg_print_lv=0 > mix_Resnet50_UNet_DeepFilters_acc_sa1.log
./maestro --print_res=true --print_res_csv_file=true --print_log_file=false --Mapping_file='data/mapping/mix_Resnet50_UNet_ShallowFilters.m' --HW_file='./data/hw/acc_het_sa2.m' --noc_hop_latency=1 --noc_mc_support=false --num_simd_lanes=1 --print_design_space=true --msg_print_lv=0 > mix_Resnet50_UNet_ShallowFilters_acc_sa2.log
 wc -l mix_Resnet50_UNet_*
